![What is NumPy](whatIsNumPy.png)

![Why NumPy](whyNumPy.png)

### Loading in NumPy

In [4]:
import numpy as np
sep ="-----------------------------------------------------------------"

In [5]:
#initialise an array

arr = np.array([1,2,3,4], dtype='int32')
print(arr)

[1 2 3 4]


In [6]:
arr2 = np.array([[1., 3., 6.],[3.,5., 7.]])
print(arr2)

[[1. 3. 6.]
 [3. 5. 7.]]


In [7]:
# get dimensions
print(arr.shape)
print(arr2.shape)
print(arr2.ndim)
print(arr.dtype)
print(arr2.dtype)

(4,)
(2, 3)
2
int32
float64


In [8]:
#get size
arr.itemsize
#total size
arr.size * arr.itemsize
#above is similar to
arr.nbytes

16

In [9]:
#applying the above to a float
arr2.nbytes

48

### Basics of Indexing  - Accessing / changing specific elements, rows, columns etc

In [10]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [11]:
#get a specific element [r,c]
a[1,5] #prints 13 or a[1, -2]

13

In [12]:
#get a specific row - first row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
#get a specific column e.g. items in the second column
a[:,2]

array([ 3, 10])

In [14]:
#getting [startindex:endIndex:Stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [15]:
#'change the content'
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [16]:
#replacing series of numbers e.g. values in a column - e.g. values in column 2
a[:,2] = [5,5]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [17]:
#working with a 3d Array
b = np.array(
 [[[1,2],
   [3,4]],
   [[5,6],
   [7,8]]]
)
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
#Getting  specific element (work outside in)
#extracting 4 from the above array
b[0,1,1]

4

In [19]:
#replacing a subsequence
b[:,1,:]  = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initialising different types of Arrays

In [20]:
#All zero matrix
print(np.zeros(5))
print(np.zeros((2,3)))
print(np.zeros ((2,3,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [21]:
#all ones matrix
print(np.ones ((4,2,1), dtype='int32'))

[[[1]
  [1]]

 [[1]
  [1]]

 [[1]
  [1]]

 [[1]
  [1]]]


In [32]:
#any other number using full, takes the shape and the values
print(np.full((2,3),99, dtype='float32'))


[[99. 99. 99.]
 [99. 99. 99.]]


In [23]:
#array creation using the full_like() method
#builds another array based on an existing array's shape
print(np.full_like(a, 4))
print(np.full_like(arr2,5))

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[5. 5. 5.]
 [5. 5. 5.]]


In [24]:
#Initialise a matrix of random numbers - passing the shape
print(np.random.rand(4,2,3))

#building random array using an existing shape
print(sep)
print(np.random.random_sample(a.shape))

[[[0.42856375 0.31892484 0.98838509]
  [0.70155513 0.40547365 0.89682181]]

 [[0.97375051 0.00682114 0.54731438]
  [0.4099619  0.26350103 0.39602353]]

 [[0.94166462 0.25824444 0.53913884]
  [0.3035908  0.88139307 0.2428717 ]]

 [[0.26771275 0.40892423 0.17603258]
  [0.52048315 0.1337023  0.49890234]]]
-----------------------------------------------------------------
[[0.43989604 0.33791336 0.19457695 0.1271081  0.83997047 0.22062606
  0.08772461]
 [0.39775835 0.99624592 0.09340686 0.20121729 0.99950711 0.12742354
  0.40137028]]


In [25]:
#random integer values
print(np.random.randint(7, size=(3,3))) #generates random numbers in the matrix up to 7
print(sep)
print(np.random.randint(4,7, size=(3,3))) #generates random numbers between 4, and 7 inclusive

[[5 3 6]
 [6 4 5]
 [2 1 1]]
-----------------------------------------------------------------
[[6 4 5]
 [5 6 4]
 [6 4 5]]


In [26]:
#identity matrix - takes one value as the identity matrix is a square matrix

print(np.identity(3))
print(sep)
print(np.identity(5))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------------------------------------------------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
#repeating an array a few times
arr3 = np.array([[1,2,3], [4,5,6]])
arr4 = np.array([[4,5,6]])
r1 = np.repeat(arr3,3, axis=0)
r2 = np.repeat(arr4,4,axis=0)
print(r1)
print(sep)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]
-----------------------------------------------------------------
[[4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


### Practice Task 
- try and initialise the matrix below
![Sample Matrix](SampleArray.png)

In [28]:
sampleArr = np.ones((5,5))
sampleArr
for i in range(1,4):
  sampleArr[i][1:4] =[0,0,0]
sampleArr[2][2] = 9
print(sampleArr)

#alternative solution
output = np.ones((5,5)) # populate full matrix
z = np.zeros((3,3)) #generate a 3x3 matrix with zeros
z[1,1] = 9
#write the 3x3 matrix into its correct position
output [1:4, 1:4] = z
print()
print(sep)
print(output)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

-----------------------------------------------------------------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
##### Copying arrays
a = np.array([1,2,3])
b = a
b
b[0] = 100 # this will alter the value in a[0] too as both b and a point to the same reference
a

b = a.copy()
b[0] = 100
print(f'a = {a}')

a = [100   2   3]


### NP Mathematics

In [30]:
a = np.array([1,2,3,4])
#element wise arithmetic
print( f'a: {a}')
print( f'a + 2: {a + 2}')
print(f'a * 2: {a * 2}')
print(f'a / 2: {a / 2}')
b = np.array([1,0,1,0])
print(sep)
print( f'b: {b}')
print(f'a + b: {a + b}') # both array must be of the same shape

print(f'a pow 2: {a**2}')

# trig functions on an np array
print(f'sin of values in a : {np.sin(a)}')
print(f'cos of values in a : {np.cos(a)}')



a: [1 2 3 4]
a + 2: [3 4 5 6]
a * 2: [2 4 6 8]
a / 2: [0.5 1.  1.5 2. ]
-----------------------------------------------------------------
b: [1 0 1 0]
a + b: [2 2 4 4]
a pow 2: [ 1  4  9 16]
sin of values in a : [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos of values in a : [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


#### Linear Algebra operations on np arrays

- Remember to multiply matrices, the column of the first matrix must be equal to rows of the second matrix
- use np.matmul() method to multiply matrices
![Matrix Multiplication](matrixMultiplication.png)
[Further Reference docs on Linear Algebra functions ](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
- Determinant
- Trace
- Singular vector decomposition
- Matrix norm
- Inverse

In [44]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2, dtype='int32')
print(b)

#multiplying a and b should result in a 2x2 matrix

print(f' a * b: {np.matmul(a, b)}')


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
 a * b: [[6. 6.]
 [6. 6.]]


In [45]:
#determinant of identity matrix - usually equal to 1
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics with numpy

In [52]:
stats = np.array([[1,2,3,4], [4,5,6,7]])
stats

print(f'Mean of Stats: {np.mean(stats)}')
print(f'Min of Stats: {np.min(stats)}')
print(f'Min of Stats on axis 1: {np.min(stats, axis=1)}')
print(f'Min of Stats on axis 0: {np.min(stats, axis=0)}')
print(f'Max of Stats: {np.max(stats)}')
print(f'Min of Stats: {np.min(stats)}')

print(sep)
print(f'Sum of Stats : {np.sum(stats)}')
print(f'Sum of Stats by row : {np.sum(stats, axis = 0)}')



Mean of Stats: 4.0
Min of Stats: 1
Min of Stats on axis 1: [1 4]
Min of Stats on axis 0: [1 2 3 4]
Max of Stats: 7
Min of Stats: 1
-----------------------------------------------------------------
Sum of Stats : 32
Sum of Stats by row : [ 5  7  9 11]


Reorganising arrays

In [57]:
before = np.array([[1,2,3,4], [4,5,6,7]])
print(before)
print(f'current shape: {before.shape}')
print(sep)

#transforming the array
after = before.reshape((4,2))
print(f'Transformed array shape: {after}')


[[1 2 3 4]
 [4 5 6 7]]
current shape: (2, 4)
-----------------------------------------------------------------
Transformed array shape: [[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [59]:
#vertically stacking matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(f'Stacked Array: {np.vstack([v1,v2,v1,v2])}')


Stacked Array: [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [62]:
#Horizontal stacking matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(f'Stacked Array: {np.hstack([v2,v1,v2])}')


Stacked Array: [5 6 7 8 1 2 3 4 5 6 7 8]


#### Miscellaneous

In [65]:
#load data from a file without using pandas
fileData = np.genfromtxt('data.txt', delimiter=',')
fileData

print(sep)
#cast data into another type
castData = fileData.astype('int32')
castData

-----------------------------------------------------------------


array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### boolean masking and advanced indexing

In [66]:
#where in file data is the value greater than 50
fileData>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [68]:
#indexing where the values match condition would return the matching values
castData [castData >50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [73]:
#indexing with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
print(f'Items at the following indices [1,2,8] in a are: {a[[1,3,8]]}')


Items at the following indices [1,2,8] in a are: [2 4 9]


In [75]:
#find out if any values in any columns are greater than 50
np.any(castData >50, axis=0) # axis = 1 would be the rows
np.all(castData > 50, axis=0) # if True if all the values in that column are greater than 50

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [81]:
#values greater than 50 but less  than 100

((castData >50) & (castData <100))
#reverse of the above
(~((castData >50) & (castData <100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

#### NumPy Final Task

![NumPy Final Task](numpyFinalTask.png)

In [92]:
a = np.arange(1,31).reshape(6,5)
a
blue = a[2:4,0:2]
print(blue)
print(sep)
green = a[[0,1,2,3], [1,2,3,4]]
print(green)
print(sep)
red  = a[[0,4,5], 3:]
print(red)

[[11 12]
 [16 17]]
-----------------------------------------------------------------
[ 2  8 14 20]
-----------------------------------------------------------------
[[ 4  5]
 [24 25]
 [29 30]]
