![What is NumPy](whatIsNumPy.png)

![Why NumPy](whyNumPy.png)

### Loading in NumPy

In [1]:
import numpy as np

In [9]:
#initialise an array

arr = np.array([1,2,3,4], dtype='int32')
print(arr)

[1 2 3 4]


In [4]:
arr2 = np.array([[1., 3., 6.],[3.,5., 7.]])
print(arr2)

[[1. 3. 6.]
 [3. 5. 7.]]


In [8]:
# get dimensions
print(arr.shape)
print(arr2.shape)
print(arr2.ndim)
print(arr.dtype)
print(arr2.dtype)

(4,)
(2, 3)
2
int32
float64


In [15]:
#get size
arr.itemsize
#total size
arr.size * arr.itemsize
#above is similar to
arr.nbytes

16

In [16]:
#applying the above to a float
arr2.nbytes

48

### Accessing / changing specific elements, rows, columns etc

In [18]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [19]:
#get a specific element [r,c]
a[1,5] #prints 13 or a[1, -2]

13

In [20]:
#get a specific row - first row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#get a specific column e.g. items in the second column
a[:,2]

array([ 3, 10])

In [22]:
#getting [startindex:endIndex:Stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [23]:
#'change the content'
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [24]:
#replacing series of numbers e.g. values in a column - e.g. values in column 2
a[:,2] = [5,5]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
