## Exercise one
Write a small Numpy array by:

- generating 10000 random numbers in a 2-dimensional array
- for each value in the array calculate the square root
- and then sum all those calculations.

In [34]:
import numpy as np
#set seed for reproducibility
np.random.seed(42)
sep ='\n--------------------------------------------------------------------------\n'
#generate 10000 random numbers into a 100x1000 array
data = np.random.randint(1,10000, size=(500,200))
print(f' random Array:\n {data[:10, :]}')

#calculate the square root of each value
square_root =np.sqrt(data)
print(sep)
print(f' Squareroot of random array:\n {square_root[:10, :]}')

#sum of random values in array
print(sep)
print(f'Total of all random values: {np.sum(data)}')
print(f'Total of all square roots: {np.sum(square_root)}')


 random Array:
 [[7271  861 5391 ... 4390 2328 8005]
 [2932 7778  198 ... 5178 9562 8933]
 [8309 5950 2839 ... 1215 1532 7577]
 ...
 [7491 9180 1219 ... 8033    2 6369]
 [1950 6733 7834 ... 7706 3720  303]
 [ 987 4441 4910 ... 9209  208 2666]]

--------------------------------------------------------------------------

 Squareroot of random array:
 [[85.27015891 29.3428015  73.4234295  ... 66.25707509 48.24935233
  89.47066558]
 [54.14794548 88.19297024 14.07124728 ... 71.95832127 97.78547949
  94.51454914]
 [91.15371633 77.1362431  53.28226722 ... 34.85685012 39.14077158
  87.04596487]
 ...
 [86.55056326 95.81231654 34.9141805  ... 89.62700486  1.41421356
  79.80601481]
 [44.15880433 82.0548597  88.50988645 ... 87.78382539 60.99180273
  17.40689519]
 [31.41655614 66.64082833 70.07139217 ... 95.96353474 14.4222051
  51.63332257]]

--------------------------------------------------------------------------

Total of all random values: 500327825
Total of all square roots: 6667763.11052614

### Exercise two

Import this [Random CSV File](RandomeValues.csv) into a program and using a NumPy array select the following data:

- All the data in rows, 5,7 and 9.
- All the data in columns 0, 7, 10.
- The data in columns 1 to 3 (exclusively), from rows 7 to 9 (inclusively).

In [35]:
fileData = np.genfromtxt("RandomValues.csv", delimiter=",")
fileData

array([[ 68.,  54.,  95.,  65.,  68.,   6.,  50.,  63.,  99.,  81.,  14.],
       [  5.,  85.,  83.,  22.,  39.,  26.,  73.,  77.,  97.,  75.,  33.],
       [  1.,  46.,  39.,  53.,  67.,  19.,  87.,   3.,  84.,  58.,  26.],
       [ 83.,  81.,  31.,  96.,  13.,   3.,  58.,  32., 100., 100.,  96.],
       [ 71.,   2.,  63.,  84.,  85.,   5.,  67.,  35.,  76.,  77.,  76.],
       [ 79.,  67.,  44., 100.,  89.,  71.,  27.,  46.,  45.,  13.,  32.],
       [100.,  27.,  23.,  76.,  53.,  86.,   2.,  59.,  30.,  52.,   2.],
       [ 37.,  43.,  10.,  16.,  77.,  40.,  62.,   4.,  22.,  64.,  15.],
       [ 97.,  61.,   8.,  99.,  67.,  42.,  59.,   7.,  86.,  42.,  21.],
       [ 80.,  93.,  76.,  46.,  46.,  35.,  57.,  70.,  93.,  36.,  86.],
       [ 25.,  23.,  89.,  58.,  89.,  52.,  21.,  65.,  52.,  25.,  45.]])

In [36]:
print(f'All data in row 5, 7 and 9: {fileData[[4,6,8],:]}')

All data in row 5, 7 and 9: [[ 71.   2.  63.  84.  85.   5.  67.  35.  76.  77.  76.]
 [100.  27.  23.  76.  53.  86.   2.  59.  30.  52.   2.]
 [ 97.  61.   8.  99.  67.  42.  59.   7.  86.  42.  21.]]


In [37]:
print(f'All data in columns 0, 7 and 10: {fileData[:,[0,7,10]]}')

All data in columns 0, 7 and 10: [[ 68.  63.  14.]
 [  5.  77.  33.]
 [  1.   3.  26.]
 [ 83.  32.  96.]
 [ 71.  35.  76.]
 [ 79.  46.  32.]
 [100.  59.   2.]
 [ 37.   4.  15.]
 [ 97.   7.  21.]
 [ 80.  70.  86.]
 [ 25.  65.  45.]]


In [38]:
print(f'All data in columns 1 to 3 exclusive, from rows 7 to 9 inclusive: {fileData[6:9,0:3]}')

All data in columns 1 to 3 exclusive, from rows 7 to 9 inclusive: [[100.  27.  23.]
 [ 37.  43.  10.]
 [ 97.  61.   8.]]


### Exercise 3
Extract from [Sales Data CSV](SalesData.csv) the column and row headers into two separate arrays. Then extract the data values into a separate 2D array. Using these 3 arrays extract the following data:

- All the sales for the second quarter (Jul-18 to Sep-18 inclusive) calculating the total and the mean for each month.
- All the sales for stores L3 and L1, for the first and third quarter calculating the total and the mean for each quarter for each store.
- All the sales for N6 and N4 that are lower than 400 and list the months in which the occur.

In [43]:
data = np.genfromtxt('SalesData.csv', delimiter=',', dtype=str)
columnHeadings = data[0,1:]
rowHeadings = data[1:,0]
mainData = data[1:,1:]
rawData = mainData.astype('int32')
print(sep)
print(f'Column Headings:\n{columnHeadings}')
print(sep)
print(f'Row Headings:\n{rowHeadings}')
print(sep)
print(f'Main Data\n{rawData}')


--------------------------------------------------------------------------

Column Headings:
['Apr-18' 'May-18' 'Jun-18' 'Jul-18' 'Aug-18' 'Sep-18' 'Oct-18' 'Nov-18'
 'Dec-18' 'Jan-19' 'Feb-19' 'Mar-19']

--------------------------------------------------------------------------

Row Headings:
['L3' 'L1' 'P2' 'N6' 'N4' 'B8']

--------------------------------------------------------------------------

Main Data
[[390 345 379 353 365 326 363 459 539 474 340 343]
 [392 377 347 395 330 332 340 446 573 464 223 216]
 [250 270 300 398 376 382 306 489 552 488 298 269]
 [460 480 450 310 392 383 314 402 640 495 215 243]
 [460 480 450 387 388 320 337 478 676 408 338 263]
 [470 510 360 472 423 385 353 464 598 419 459 659]]


In [52]:
#All the sales for the second quarter (Jul-18 to Sep-18 inclusive) 
#calculating the total and the mean for each month.
secondQtrData = rawData[0:,3:6]
print(f'Second Quarter data: {secondQtrData}')
print(f'Second Quarter Total Sales: {np.sum(secondQtrData)}')
for i in range(3,6):
  print(f'{columnHeadings[i]} total sales: {np.sum(rawData[0:,i])}')
  print(f'{columnHeadings[i]} total sales: {np.mean(rawData[0:,i]):.3f}')
  print(sep)


Second Quarter data: [[353 365 326]
 [395 330 332]
 [398 376 382]
 [310 392 383]
 [387 388 320]
 [472 423 385]]
Second Quarter Total Sales: 6717
Jul-18 total sales: 2315
Jul-18 total sales: 385.833

--------------------------------------------------------------------------

Aug-18 total sales: 2274
Aug-18 total sales: 379.000

--------------------------------------------------------------------------

Sep-18 total sales: 2128
Sep-18 total sales: 354.667

--------------------------------------------------------------------------



In [62]:
#All the sales for stores L3 and L1, 
# for the first and third quarter calculating the total 
# and the mean for each quarter for each store.

L1_SalesData_first_third_qtr =rawData[1,[0,1,2,6,7,8]]
L3_SalesData_first_third_qtr =rawData[0,[0,1,2,6,7,8]]
print(f'{L1_SalesData_first_third_qtr} |{L3_SalesData_first_third_qtr}' )
print(sep)
print(f'Total sales for L1 Store for 1st and 3rd Quarter : {np.sum(L1_SalesData_first_third_qtr)}')
print(f'Mean sales for L1 Store for 1st and 3rd Quarter : {np.mean(L1_SalesData_first_third_qtr)}')
print(sep)
print(f'Total sales for L3 Store for 1st and 3rd Quarter : {np.sum(L3_SalesData_first_third_qtr)}')
print(f'Mean sales for L3 Store for 1st and 3rd Quarter : {np.mean(L3_SalesData_first_third_qtr)}')

[392 377 347 340 446 573] |[390 345 379 363 459 539]

--------------------------------------------------------------------------

Total sales for L1 Store for 1st and 3rd Quarter : 2475
Mean sales for L1 Store for 1st and 3rd Quarter : 412.5

--------------------------------------------------------------------------

Total sales for L3 Store for 1st and 3rd Quarter : 2475
Mean sales for L3 Store for 1st and 3rd Quarter : 412.5


#### Exercise four
The random walk problem can be used as an interesting investigation into probability. Consider the following:

- A bug lives in the middle of a long thin island where it can only move left or right. The island is 7 units (steps) long. If the bug reaches the edge of the island in either direction it will fall off and drown in the sea. The bug can only move one step in either direction. If the direction is randomly selected how many steps will it take before the bug falls off?
- Investigate ‘random walks’ and using the code in the core text as a starting point write a program to test the above scenario over 100 iterations. Collect the step count in an appropriate structure and then apply appropriate statistics to describe this data.

In [91]:
#Plan
#simulate the bugs movements over 100 iterations and collect the step count in each iteration
#analyse the data to describe the bug's behaviour

import random
def random_walk(steps=7):
  pos = 0
  step_count = 0
  
  while pos != -steps and pos != steps:
    direction = random.choice([-1,1]) # where -1 = Left and 1 = right
    pos += direction
    step_count +=1
  return step_count
def simulate_random_walks(iterations=100):
  step_counts = []
  
  for _ in range(iterations):
    step_count =random_walk()
    step_counts.append(step_count)
    return step_counts

def analyse_random_walks(step_counts):
  average_steps = sum(step_counts)/len(step_counts)
  max_steps = max(step_counts)
  min_steps = min(step_counts)
  
  print(f'Average steps: {average_steps}')
  print(f'Maximum steps: {max_steps}')
  print(f'Min steps: {min_steps}')
  
if __name__ == "__main__":
  iterations = 100
  step_counts = simulate_random_walks(iterations)
  analyse_random_walks(step_counts)

Average steps: 15.0
Maximum steps: 15
Min steps: 15


In [80]:
simulate_random_walks()

[29]

### Exercise five

Investigate what sorting algorithms are used by numpy.sort() function and write a short summary (about 200words) of which you would use for datasets with particular features, such as size, and why?

 - numpy.sort() - uses a hybrid between quick sort and  heapsort to achieve efficient sorting performance.
 - Starts with quick sort switching to heap sort if the recursion depth is exceeded leading to a worst case  performance of O(nlog(n))
 - For small datasets  the choice of sorting is not critical and both quick sort and heap sorts perform well on small datasets.
 -The ability to switch becomes advantageous with large datasets which leads to reliable performance regardless of the data distribution